server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/umbrella-database
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
cache:
  limit: 100

logging:
  level:
    root: INFO
  file:
    name: logs/myapp.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

