server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/umbrella-database
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
cache:
  limit: 100

